import React from 'react';
import Markdown from 'react-markdown';
import { Language } from '../translations';
 
interface PrivacyPolicyProps {
  lang: Language;
}
 
export default function PrivacyPolicy({ lang }: PrivacyPolicyProps) {
  const lastUpdated = 'May 2026';
  const content = `
*Last updated: ${lastUpdated}*
 
This Privacy Policy explains how FlightComp ("we", "us", "the service") handles information when you use our flight compensation calculator at flightcompensationcalc.com.
 
We are committed to processing as little personal data as possible. This service is **free**, **does not require an account**, and **does not sell your data**.
 
## 1. Information We Process
 
When you use the calculator, you may enter the following information:
 
- Flight details: airline, flight number, departure and arrival airports, scheduled and actual times
- Disruption details: type of disruption (delay, cancellation, denied boarding), length of delay, reason given by the airline
- Optional contact details if you choose to share them with us
 
We do **not** ask for your full name, address, passport number, or payment information through this calculator.
 
## 2. How Data Is Used
 
The information you enter is used **only** to:
 
- Calculate your potential compensation eligibility under EC 261/2004 and UK261
- Display the result to you in the browser
- Improve the calculator's accuracy in aggregate (for example, knowing which airlines and routes are most queried)
 
We do not use your inputs for advertising, profiling, or resale.
 
## 3. Third-Party Services
 
The calculator may use the following third-party services:
 
- **Google Gemini AI** — Some explanations and helper text may be generated by Google's Gemini API. When this happens, your flight details (without your name) may be sent to Google to produce the explanation. Google's processing is governed by [Google's Privacy Policy](https://policies.google.com/privacy).
- **Vercel** — Our hosting provider. Vercel may collect basic technical data such as IP address and browser type for security and analytics. See [Vercel's Privacy Policy](https://vercel.com/legal/privacy-policy).
 
We do not use Google Analytics, Facebook Pixel, or other advertising trackers.
 
## 4. Cookies
 
This site uses **only essential cookies** required for the application to function. We do **not** set tracking or marketing cookies.
 
## 5. Data Retention
 
- Form inputs are processed in your browser and are not permanently stored on our servers
- Server logs (IP address, request time) are kept for up to 30 days for security and abuse prevention, then deleted
- If you contact us by email, we retain that email until the matter is resolved
 
## 6. Your Rights Under GDPR
 
If you are in the European Economic Area or the United Kingdom, you have the right to:
 
- Access any personal data we hold about you
- Request correction of inaccurate data
- Request deletion of your data ("right to be forgotten")
- Object to processing
- Lodge a complaint with your national data protection authority (in Latvia: **Datu valsts inspekcija**)
 
To exercise these rights, contact us using the email below.
 
## 7. Children
 
This service is not intended for children under 16. We do not knowingly collect data from minors.
 
## 8. International Transfers
 
If data is sent to Google Gemini, it may be processed outside the EU. We rely on the standard contractual clauses provided by Google for any such transfers.
 
## 9. Changes to This Policy
 
We may update this Privacy Policy. The "Last updated" date at the top reflects the most recent version. Material changes will be highlighted on the home page for at least 14 days.
 
## 10. Contact
 
If you have questions about this Privacy Policy or your data, please contact us through the email listed in the GitHub repository for this project.
`;
 
  return (
    <div className="max-w-4xl mx-auto px-4 py-20">
      <h1 className="text-4xl font-black text-brand-navy mb-8">Privacy Policy</h1>
      <div className="markdown-body prose lg:prose-xl text-slate-700">
        <Markdown>{content}</Markdown>
      </div>
    </div>
  );
}
 

