import React from 'react';
import Markdown from 'react-markdown';
import { Language } from '../translations';

interface PrivacyPolicyProps {
  lang: Language;
}

const lastUpdated = 'May 2026';

const titles: Record<Language, string> = {
  en: 'Privacy Policy',
  lv: 'Privātuma politika',
  de: 'Datenschutzerklärung',
  fr: 'Politique de confidentialité',
  es: 'Política de privacidad',
};

const contentByLang: Record<Language, string> = {
  en: `
*Last updated: ${lastUpdated}*

This Privacy Policy explains how FlightComp ("we", "us", "the service") handles information when you use our flight compensation calculator at flightcompensationcalc.com.

We are committed to processing as little personal data as possible. This service is **free**, **does not require an account**, and **does not sell your data**.

## 1. Information We Process

When you use the calculator, you may enter the following information:

- Flight details: airline, flight number, departure and arrival airports, scheduled and actual times
- Disruption details: type of disruption (delay, cancellation, denied boarding), length of delay, reason given by the airline
- Optional contact details if you choose to share them with us

We do **not** ask for your full name, address, passport number, or payment information through this calculator.

## 2. How Data Is Used

The information you enter is used **only** to:

- Calculate your potential compensation eligibility under EC 261/2004 and UK261
- Display the result to you in the browser
- Improve the calculator's accuracy in aggregate

We do not use your inputs for advertising, profiling, or resale.

## 3. Third-Party Services

The calculator may use the following third-party services:

- **Google Gemini AI** — Some explanations may be generated by Google's Gemini API. Your flight details (without your name) may be sent to Google. See [Google's Privacy Policy](https://policies.google.com/privacy).
- **Vercel** — Our hosting provider. May collect basic technical data (IP address, browser type) for security and operations. See [Vercel's Privacy Policy](https://vercel.com/legal/privacy-policy).
- **Vercel Web Analytics** — Privacy-friendly analytics that collects aggregated visitor data (page views, country, device, referrer). **Does not use cookies, does not track you across sites, no personal identifiers.** See [Vercel Analytics Privacy](https://vercel.com/docs/analytics/privacy-policy).

We do not use Google Analytics, Facebook Pixel, or any advertising or cross-site tracking services.

## 4. Cookies

This site uses **only essential cookies** required for the application to function. We do **not** set tracking, advertising, or marketing cookies. Vercel Web Analytics operates without cookies.

## 5. Data Retention

- Form inputs are processed in your browser and are not permanently stored on our servers
- Server logs (IP, request time) are kept up to 30 days for security and abuse prevention, then deleted
- Vercel Analytics data follows Vercel's retention policy (typically aggregated)
- Email contacts are retained until the matter is resolved

## 6. Your Rights Under GDPR

If you are in the EEA or UK, you have the right to:

- Access your personal data
- Request correction
- Request deletion ("right to be forgotten")
- Object to processing
- Lodge a complaint with your national data protection authority

## 7. Children

This service is not intended for children under 16. We do not knowingly collect data from minors.

## 8. International Transfers

If data is sent to Google Gemini or processed by Vercel, it may be processed outside the EU. We rely on the standard contractual clauses provided by these vendors.

## 9. Changes to This Policy

We may update this Privacy Policy. The "Last updated" date reflects the most recent version. Material changes will be highlighted on the home page for at least 14 days.

## 10. Contact

For questions about this Privacy Policy or your data, contact us through the email listed in our GitHub repository.
`,
  lv: `
*Pēdējoreiz atjaunināts: ${lastUpdated}*

Šī Privātuma politika izskaidro, kā FlightComp ("mēs", "pakalpojums") rīkojas ar informāciju, kad jūs izmantojat mūsu lidojumu kompensācijas kalkulatoru vietnē flightcompensationcalc.com.

Mēs apņemamies apstrādāt pēc iespējas mazāk personas datu. Šis pakalpojums ir **bezmaksas**, **neprasa kontu** un **nepārdod jūsu datus**.

## 1. Kādu informāciju mēs apstrādājam

Lietojot kalkulatoru, jūs varat ievadīt šādu informāciju:

- Lidojuma informācija: aviokompānija, reisa numurs, izlidošanas un ielidošanas lidostas, plānotie un faktiskie laiki
- Traucējuma informācija: traucējuma veids (kavējums, atcelšana, atteikta iekāpšana), kavējuma ilgums, aviokompānijas norādītais iemesls
- Pēc izvēles kontaktinformācija, ja jūs to mums uzticat

Mēs **neprasām** jūsu pilnu vārdu, adresi, pases numuru vai maksājumu informāciju.

## 2. Kā dati tiek izmantoti

Jūsu ievadītā informācija tiek izmantota **tikai**, lai:

- Aprēķinātu jūsu iespējamās tiesības uz kompensāciju saskaņā ar EC 261/2004 un UK261
- Parādītu rezultātu jūsu pārlūkā
- Uzlabotu kalkulatora precizitāti agregātā

Mēs nelietojam jūsu datus reklāmai, profilēšanai vai pārdošanai.

## 3. Trešo pušu pakalpojumi

Kalkulators var izmantot šādus trešo pušu pakalpojumus:

- **Google Gemini AI** — Daži paskaidrojumi var tikt ģenerēti, izmantojot Google Gemini API. Jūsu lidojuma informācija (bez vārda) var tikt nosūtīta Google. Skatīt [Google privātuma politiku](https://policies.google.com/privacy).
- **Vercel** — Mūsu hostinga pakalpojuma sniedzējs. Var apkopot pamata tehniskos datus (IP adrese, pārlūka veids) drošības un darbības nolūkos. Skatīt [Vercel privātuma politiku](https://vercel.com/legal/privacy-policy).
- **Vercel Web Analytics** — Privātumam draudzīga analītika, kas apkopo agregētus apmeklētāju datus (lapu skatījumi, valsts, ierīce, atsauces avots). **Neizmanto sīkdatnes, nepiedalās starpsvietņu izsekošanā, bez personiskiem identifikatoriem.** Skatīt [Vercel Analytics privātumu](https://vercel.com/docs/analytics/privacy-policy).

Mēs nelietojam Google Analytics, Facebook Pixel vai citus reklāmas/izsekošanas pakalpojumus.

## 4. Sīkdatnes

Šī vietne lieto **tikai būtiskās sīkdatnes**, kas nepieciešamas lietotnes darbībai. Mēs **neuzstādām** izsekošanas, reklāmas vai mārketinga sīkdatnes. Vercel Web Analytics darbojas bez sīkdatnēm.

## 5. Datu saglabāšana

- Formas ievades tiek apstrādātas jūsu pārlūkā un netiek pastāvīgi glabātas mūsu serveros
- Servera žurnāli (IP, pieprasījuma laiks) tiek glabāti līdz 30 dienām drošības un ļaunprātības novēršanai, pēc tam dzēsti
- Vercel Analytics dati tiek glabāti saskaņā ar Vercel politiku (parasti agregēti)
- E-pasta saziņa tiek saglabāta, līdz jautājums atrisināts

## 6. Jūsu tiesības saskaņā ar VDAR

Ja jūs atrodaties EEZ vai AK, jums ir tiesības:

- Piekļūt saviem personas datiem
- Pieprasīt labojumus
- Pieprasīt dzēšanu ("tiesības tikt aizmirstam")
- Iebilst pret apstrādi
- Iesniegt sūdzību savā valsts datu aizsardzības iestādē (Latvijā: **Datu valsts inspekcija**)

## 7. Bērni

Pakalpojums nav paredzēts bērniem līdz 16 gadu vecumam. Mēs apzināti nevācam datus no nepilngadīgajiem.

## 8. Starptautiska datu pārsūtīšana

Ja dati tiek nosūtīti Google Gemini vai apstrādāti Vercel, tie var tikt apstrādāti ārpus ES. Mēs paļaujamies uz standarta līgumiskajām klauzulām, ko nodrošina šie pakalpojumu sniedzēji.

## 9. Politikas izmaiņas

Mēs varam atjaunināt šo Privātuma politiku. Datums "Pēdējoreiz atjaunināts" atspoguļo jaunāko versiju. Būtiskas izmaiņas tiks izceltas sākumlapā vismaz 14 dienas.

## 10. Kontakti

Jautājumiem par šo Privātuma politiku vai jūsu datiem, sazinieties ar mums caur e-pastu, kas norādīts mūsu GitHub repozitorijā.
`,
  de: `
*Zuletzt aktualisiert: ${lastUpdated}*

Diese Datenschutzerklärung erläutert, wie FlightComp ("wir", "uns", "der Dienst") mit Informationen umgeht, wenn Sie unseren Entschädigungsrechner unter flightcompensationcalc.com nutzen.

Wir verpflichten uns, so wenig personenbezogene Daten wie möglich zu verarbeiten. Dieser Dienst ist **kostenlos**, **erfordert kein Konto** und **verkauft Ihre Daten nicht**.

## 1. Welche Informationen wir verarbeiten

Bei der Nutzung des Rechners können Sie folgende Informationen eingeben:

- Flugdetails: Fluggesellschaft, Flugnummer, Abflug- und Zielflughafen, planmäßige und tatsächliche Zeiten
- Störungsdetails: Art der Störung (Verspätung, Annullierung, Nichtbeförderung), Verspätungsdauer, vom Carrier angegebener Grund
- Optionale Kontaktdaten, falls Sie diese mit uns teilen möchten

Wir fragen **nicht** nach Ihrem vollständigen Namen, Ihrer Adresse, Pass- oder Zahlungsdaten.

## 2. Wie die Daten verwendet werden

Die von Ihnen eingegebenen Informationen werden **nur** verwendet, um:

- Ihren möglichen Entschädigungsanspruch nach EC 261/2004 und UK261 zu berechnen
- Das Ergebnis im Browser anzuzeigen
- Die Genauigkeit des Rechners aggregiert zu verbessern

Wir verwenden Ihre Eingaben nicht für Werbung, Profiling oder Weiterverkauf.

## 3. Drittanbieter-Dienste

Der Rechner kann folgende Drittanbieter-Dienste nutzen:

- **Google Gemini AI** — Manche Erklärungen werden von Googles Gemini-API erstellt. Ihre Flugdetails (ohne Ihren Namen) können an Google gesendet werden. Siehe [Googles Datenschutzerklärung](https://policies.google.com/privacy).
- **Vercel** — Unser Hosting-Anbieter. Kann grundlegende technische Daten (IP-Adresse, Browser-Typ) zu Sicherheits- und Betriebszwecken erfassen. Siehe [Vercels Datenschutzerklärung](https://vercel.com/legal/privacy-policy).
- **Vercel Web Analytics** — Datenschutzfreundliche Analyse, die aggregierte Besucherdaten (Seitenaufrufe, Land, Gerät, Referrer) erfasst. **Verwendet keine Cookies, kein Tracking über Websites hinweg, keine persönlichen Identifikatoren.** Siehe [Vercel Analytics Datenschutz](https://vercel.com/docs/analytics/privacy-policy).

Wir verwenden weder Google Analytics noch Facebook Pixel noch andere Werbe- oder Tracking-Dienste.

## 4. Cookies

Diese Website verwendet **nur essenzielle Cookies**, die für das Funktionieren der Anwendung erforderlich sind. Wir setzen **keine** Tracking-, Werbe- oder Marketing-Cookies. Vercel Web Analytics arbeitet ohne Cookies.

## 5. Datenspeicherung

- Formulareingaben werden im Browser verarbeitet und nicht dauerhaft auf unseren Servern gespeichert
- Server-Logs (IP, Anfragezeit) werden bis zu 30 Tage zur Sicherheits- und Missbrauchsvermeidung aufbewahrt, dann gelöscht
- Vercel Analytics-Daten unterliegen Vercels Aufbewahrungsrichtlinie (typischerweise aggregiert)
- E-Mail-Kontakte werden aufbewahrt, bis das Anliegen geklärt ist

## 6. Ihre Rechte nach DSGVO

Wenn Sie sich im EWR oder im Vereinigten Königreich befinden, haben Sie das Recht:

- Auf Ihre personenbezogenen Daten zuzugreifen
- Berichtigung zu verlangen
- Löschung zu verlangen ("Recht auf Vergessenwerden")
- Der Verarbeitung zu widersprechen
- Bei Ihrer nationalen Datenschutzbehörde Beschwerde einzulegen (in Deutschland: BfDI — Bundesbeauftragter für den Datenschutz und die Informationsfreiheit)

## 7. Kinder

Dieser Dienst ist nicht für Kinder unter 16 Jahren gedacht. Wir erheben wissentlich keine Daten von Minderjährigen.

## 8. Internationale Datenübermittlung

Wenn Daten an Google Gemini gesendet oder durch Vercel verarbeitet werden, können sie außerhalb der EU verarbeitet werden. Wir verlassen uns auf die von diesen Anbietern bereitgestellten Standardvertragsklauseln.

## 9. Änderungen dieser Erklärung

Wir können diese Datenschutzerklärung aktualisieren. Das Datum "Zuletzt aktualisiert" spiegelt die neueste Version wider. Wesentliche Änderungen werden mindestens 14 Tage auf der Startseite hervorgehoben.

## 10. Kontakt

Bei Fragen zu dieser Datenschutzerklärung oder Ihren Daten kontaktieren Sie uns über die in unserem GitHub-Repository angegebene E-Mail-Adresse.
`,
  fr: `
*Dernière mise à jour : ${lastUpdated}*

Cette Politique de confidentialité explique comment FlightComp ("nous", "le service") traite les informations lorsque vous utilisez notre calculateur d'indemnisation à flightcompensationcalc.com.

Nous nous engageons à traiter le moins de données personnelles possible. Ce service est **gratuit**, **ne nécessite pas de compte** et **ne vend pas vos données**.

## 1. Informations que nous traitons

Lors de l'utilisation du calculateur, vous pouvez saisir :

- Détails du vol : compagnie aérienne, numéro de vol, aéroports de départ et d'arrivée, heures prévues et réelles
- Détails de la perturbation : type (retard, annulation, refus d'embarquement), durée du retard, motif donné par la compagnie
- Coordonnées facultatives si vous choisissez de les partager

Nous **ne demandons pas** votre nom complet, adresse, numéro de passeport ou informations de paiement.

## 2. Utilisation des données

Les informations saisies sont utilisées **uniquement** pour :

- Calculer votre éligibilité à une indemnisation au titre du règlement CE 261/2004 et UK261
- Afficher le résultat dans votre navigateur
- Améliorer la précision du calculateur de manière agrégée

Nous n'utilisons pas vos saisies à des fins publicitaires, de profilage ou de revente.

## 3. Services tiers

Le calculateur peut utiliser les services tiers suivants :

- **Google Gemini AI** — Certaines explications peuvent être générées par l'API Gemini de Google. Vos détails de vol (sans votre nom) peuvent être envoyés à Google. Voir la [Politique de confidentialité de Google](https://policies.google.com/privacy).
- **Vercel** — Notre hébergeur. Peut collecter des données techniques de base (adresse IP, type de navigateur) à des fins de sécurité et d'exploitation. Voir la [Politique de confidentialité de Vercel](https://vercel.com/legal/privacy-policy).
- **Vercel Web Analytics** — Service d'analyse respectueux de la vie privée qui collecte des données agrégées (pages vues, pays, appareil, source de référence). **N'utilise pas de cookies, ne suit pas entre les sites, aucun identifiant personnel.** Voir la [Confidentialité Vercel Analytics](https://vercel.com/docs/analytics/privacy-policy).

Nous n'utilisons pas Google Analytics, Facebook Pixel ni aucun service publicitaire ou de suivi inter-sites.

## 4. Cookies

Ce site utilise **uniquement des cookies essentiels** nécessaires au fonctionnement de l'application. Nous **n'installons pas** de cookies de suivi, publicitaires ou marketing. Vercel Web Analytics fonctionne sans cookies.

## 5. Conservation des données

- Les saisies de formulaire sont traitées dans votre navigateur et ne sont pas conservées de manière permanente sur nos serveurs
- Les journaux serveur (IP, heure de requête) sont conservés jusqu'à 30 jours pour la sécurité et la prévention des abus, puis supprimés
- Les données Vercel Analytics suivent la politique de Vercel (généralement agrégées)
- Les e-mails de contact sont conservés jusqu'à la résolution du sujet

## 6. Vos droits selon le RGPD

Si vous êtes dans l'EEE ou au Royaume-Uni, vous avez le droit :

- D'accéder à vos données personnelles
- De demander une rectification
- De demander la suppression ("droit à l'oubli")
- De vous opposer au traitement
- De déposer une plainte auprès de votre autorité nationale (en France : la CNIL — Commission nationale de l'informatique et des libertés)

## 7. Enfants

Ce service ne s'adresse pas aux enfants de moins de 16 ans. Nous ne collectons pas sciemment de données auprès de mineurs.

## 8. Transferts internationaux

Si des données sont envoyées à Google Gemini ou traitées par Vercel, elles peuvent être traitées hors de l'UE. Nous nous appuyons sur les clauses contractuelles types fournies par ces fournisseurs.

## 9. Modifications de cette politique

Nous pouvons mettre à jour cette Politique de confidentialité. La date "Dernière mise à jour" reflète la version la plus récente. Les changements importants seront signalés sur la page d'accueil pendant au moins 14 jours.

## 10. Contact

Pour toute question concernant cette Politique de confidentialité ou vos données, contactez-nous via l'e-mail indiqué dans notre dépôt GitHub.
`,
  es: `
*Última actualización: ${lastUpdated}*

Esta Política de privacidad explica cómo FlightComp ("nosotros", "el servicio") gestiona la información cuando usted usa nuestra calculadora de indemnización en flightcompensationcalc.com.

Nos comprometemos a procesar la menor cantidad de datos personales posible. Este servicio es **gratuito**, **no requiere cuenta** y **no vende sus datos**.

## 1. Información que procesamos

Al usar la calculadora, puede introducir:

- Detalles del vuelo: aerolínea, número de vuelo, aeropuertos de salida y llegada, horarios previstos y reales
- Detalles de la incidencia: tipo (retraso, cancelación, denegación de embarque), duración del retraso, motivo dado por la aerolínea
- Datos de contacto opcionales si decide compartirlos

**No pedimos** su nombre completo, dirección, número de pasaporte ni datos de pago.

## 2. Cómo se usan los datos

La información que introduce se usa **únicamente** para:

- Calcular su posible derecho a indemnización según CE 261/2004 y UK261
- Mostrar el resultado en su navegador
- Mejorar la precisión de la calculadora de forma agregada

No usamos sus datos para publicidad, elaboración de perfiles o reventa.

## 3. Servicios de terceros

La calculadora puede usar los siguientes servicios de terceros:

- **Google Gemini AI** — Algunas explicaciones pueden ser generadas por la API Gemini de Google. Sus datos de vuelo (sin su nombre) pueden enviarse a Google. Ver la [Política de privacidad de Google](https://policies.google.com/privacy).
- **Vercel** — Nuestro proveedor de hosting. Puede recopilar datos técnicos básicos (dirección IP, tipo de navegador) por motivos de seguridad y operativos. Ver la [Política de privacidad de Vercel](https://vercel.com/legal/privacy-policy).
- **Vercel Web Analytics** — Analítica respetuosa con la privacidad que recopila datos agregados (páginas vistas, país, dispositivo, fuente de referencia). **No usa cookies, no rastrea entre sitios, sin identificadores personales.** Ver [Privacidad de Vercel Analytics](https://vercel.com/docs/analytics/privacy-policy).

No usamos Google Analytics, Facebook Pixel ni ningún servicio de publicidad o rastreo entre sitios.

## 4. Cookies

Este sitio usa **solo cookies esenciales** necesarias para el funcionamiento de la aplicación. **No instalamos** cookies de seguimiento, publicidad ni marketing. Vercel Web Analytics funciona sin cookies.

## 5. Conservación de datos

- Las entradas de formulario se procesan en su navegador y no se almacenan permanentemente en nuestros servidores
- Los registros del servidor (IP, hora de solicitud) se conservan hasta 30 días por seguridad y prevención de abusos, luego se eliminan
- Los datos de Vercel Analytics siguen la política de Vercel (normalmente agregados)
- Los correos electrónicos de contacto se conservan hasta resolver el asunto

## 6. Sus derechos bajo el RGPD

Si se encuentra en el EEE o el Reino Unido, tiene derecho a:

- Acceder a sus datos personales
- Solicitar rectificación
- Solicitar la supresión ("derecho al olvido")
- Oponerse al tratamiento
- Presentar una reclamación ante su autoridad nacional (en España: AEPD — Agencia Española de Protección de Datos)

## 7. Menores

Este servicio no está dirigido a menores de 16 años. No recopilamos datos de menores conscientemente.

## 8. Transferencias internacionales

Si los datos se envían a Google Gemini o son procesados por Vercel, pueden tratarse fuera de la UE. Nos basamos en las cláusulas contractuales tipo proporcionadas por estos proveedores.

## 9. Cambios en esta política

Podemos actualizar esta Política de privacidad. La fecha "Última actualización" refleja la versión más reciente. Los cambios importantes se destacarán en la página de inicio durante al menos 14 días.

## 10. Contacto

Para preguntas sobre esta Política de privacidad o sus datos, contáctenos a través del correo electrónico indicado en nuestro repositorio de GitHub.
`,
};

export default function PrivacyPolicy({ lang }: PrivacyPolicyProps) {
  const content = contentByLang[lang] || contentByLang.en;
  const title = titles[lang] || titles.en;

  return (
    <div className="max-w-4xl mx-auto px-4 py-20">
      <h1 className="text-4xl font-black text-brand-navy mb-8">{title}</h1>
      <div className="markdown-body prose lg:prose-xl text-slate-700">
        <Markdown>{content}</Markdown>
      </div>
    </div>
  );
}
